import Head from "next/head";
import Carousel from "react-material-ui-carousel";
import { CarouselSlide } from "../components/Carousel";
import { Landing } from "../components/Landing";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
    </>
  );
}
