import Head from "next/head";
import Carousel from "react-material-ui-carousel";
import { CarouselSlide } from "../components/Carousel";
import { Landing } from "../components/Landing";

export default function Home() {
  return (
    <>
      <div className="background -z-10">
        <div className="shape"></div>
        <div className="shape"></div>
      </div>
      <div className="backdrop-filter backdrop-blur-sm bg-opacity-50 max-w-screen overflow-hidden max-h-screen">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Landing />
      </div>
    </>
  );
}
